# Handle integ test pipeline status

name: handle-integ-test-pipeline-status
on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'The commit ID triggered from CodePipeline'
        required: true
      pipeline_state:
        description: 'The state of the pipeline (success or failure)'
        required: true
      pr_number:
        description: 'The PR number to update check status'
        required: true
      ref:
        description: 'The ref of the branch that was tested'
        required: true

jobs:
  handle_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Print inputs
        run: |
          echo "Commit ID: ${{ github.event.inputs.commit_id }}"
          echo "Pipeline State: ${{ github.event.inputs.pipeline_state }}"
      
      # Add steps to handle the status or take actions based on the state
      - name: Fail on integ-test-pipeline failure
        if: ${{ github.event.inputs.pipeline_state == 'failure' }}
        run: |
          echo "Integ-test Pipeline failed. Marking workflow as failed."
          exit 1  # This will fail the workflow
        
      - name: Notify on success
        if: ${{ github.event.inputs.pipeline_state == 'success' }}
        run: |
          echo "Pipeline succeeded"
      
      - name: Add status check to the PR
        run: |
          echo "Adding check status to PR #${{ github.event.inputs.pr_number }}"

          # Use GitHub API to update the commit status (this will link the status to the PR)
          curl -X POST \
            -H "Authorization: token ${{ secrets.PROJEN_GITHUB_TOKEN }}" \
            -d '{"state": "${{ github.event.inputs.pipeline_state }}", "description": "Pipeline status", "context": "ci/integ-test", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.inputs.commit_id }}"
