# Request a deployment to the integ test pipeline

name: request-integ-test
on:
  pull_request_target: {}

jobs:
  submit-to-integ-test-pipeline:
    environment: integ-test-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needs to run with PROJEN_GITHUB_TOKEN because we need permissions to force push the branch
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Submit to integ-test-pipeline
        run: |
          git config --global user.name 'aws-cdk-automation'
          git config --global user.email 'aws-cdk-automation@users.noreply.github.com'
          git push --force --atomic https://github.com/${{ github.repository }}.git FETCH_HEAD:integ-test-pipeline
      - name: Explain next steps
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          message: |
            :arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

            A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
          comment-tag: request-cli-integ-test
          mode: recreate
          # Post as our automation user
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
