# Request a deployment to the integ test branch

name: request-integ-test
on:
  pull_request_target: {}

jobs:
  submit-to-integ-test-pipeline:
    environment: integ-test-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needs to run with PROJEN_GITHUB_TOKEN because we need permissions to force push the branch
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      
      - name: Push to test branch
        run: |
          git config --global user.name 'aws-cdk-automation'
          git config --global user.email 'aws-cdk-automation@users.noreply.github.com'

          # Test branch for the PR using the format 'integ-test/pr-{pr_number}'
          BRANCH_NAME="integ-test/pr-${{ github.event.pull_request.number }}"

          # Fetch the latest branches from the remote
          git fetch origin
          
          # Check if the branch exists on the remote
          if git branch -r | grep "origin/$BRANCH_NAME"; then
            echo "Branch $BRANCH_NAME exists, pushing to it."
            # Push FETCH_HEAD to the existing test branch
            git push --force --atomic https://github.com/${{ github.repository }}.git FETCH_HEAD:$BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist, creating and pushing it."
            git checkout -b $BRANCH_NAME
            git push --set-upstream origin $BRANCH_NAME
          fi

      - name: Create Check Run on PR Source Branch
        id: create_check_run
        run: |
          # Create a GitHub check run on the source branch (the branch from which PR is created)
          curl -X POST -H "Authorization: token ${{ secrets.PROJEN_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                "name": "Integ Test Deployment Status",
                "head_sha": "${{ github.event.pull_request.head.sha }}",  # PR source branch commit ID
                "status": "in_progress",  # Initial status of the check run
                "external_id": "pipeline-${{ github.event.pull_request.number }}",
                "context": "CI/CD Pipeline"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/check-runs"

      - name: Explain next steps
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          message: |
            :arrow_right: **Integ test deployment request submitted to `integ-test-pipeline`** :arrow_left:

            A maintainer must now check the pipeline and add the `pr-linter/integ-test-checked` label once the pipeline succeeds.
          comment-tag: request-integ-test
          mode: recreate
          # Post as our automation user
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
